// <auto-generated />
using System;
using FoodStoreMarket.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodStoreMarket.Persistance.Migrations
{
    [DbContext(typeof(FoodStoreMarketDbContext))]
    [Migration("20211226004000_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FoodStoreMarket.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Inactivated")
                        .HasColumnType("datetime2");

                    b.Property<string>("InactivatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("FoodStoreMarket.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Inactivated")
                        .HasColumnType("datetime2");

                    b.Property<string>("InactivatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RestaurantSpecificationId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantSpecificationId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2021, 12, 26, 1, 40, 0, 358, DateTimeKind.Local).AddTicks(4385),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RestaurantSpecificationId = 1,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2021, 12, 26, 1, 40, 0, 358, DateTimeKind.Local).AddTicks(4643),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RestaurantSpecificationId = 1,
                            StatusId = 1
                        });
                });

            modelBuilder.Entity("FoodStoreMarket.Domain.Entities.Indegriment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Inactivated")
                        .HasColumnType("datetime2");

                    b.Property<string>("InactivatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Indegriments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2021, 12, 26, 1, 40, 0, 358, DateTimeKind.Local).AddTicks(5822),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mutton meat",
                            Price = 0m,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2021, 12, 26, 1, 40, 0, 358, DateTimeKind.Local).AddTicks(5831),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Chicken meat",
                            Price = 0m,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2021, 12, 26, 1, 40, 0, 358, DateTimeKind.Local).AddTicks(5836),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Salad",
                            Price = 0m,
                            StatusId = 1
                        });
                });

            modelBuilder.Entity("FoodStoreMarket.Domain.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Inactivated")
                        .HasColumnType("datetime2");

                    b.Property<string>("InactivatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId")
                        .IsUnique();

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2021, 12, 26, 1, 40, 0, 358, DateTimeKind.Local).AddTicks(5729),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RestaurantId = 1,
                            StatusId = 1
                        });
                });

            modelBuilder.Entity("FoodStoreMarket.Domain.Entities.OpeningClosingHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Inactivated")
                        .HasColumnType("datetime2");

                    b.Property<string>("InactivatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OpeningClosingSpecificationId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OpeningClosingSpecificationId");

                    b.ToTable("OpeningClosingHours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2021, 12, 26, 1, 40, 0, 358, DateTimeKind.Local).AddTicks(4846),
                            Day = "Monday",
                            IsOpen = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OpeningClosingSpecificationId = 1,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2021, 12, 26, 1, 40, 0, 358, DateTimeKind.Local).AddTicks(5036),
                            Day = "Tuesday",
                            IsOpen = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OpeningClosingSpecificationId = 1,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2021, 12, 26, 1, 40, 0, 358, DateTimeKind.Local).AddTicks(5220),
                            Day = "Wednesday",
                            IsOpen = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OpeningClosingSpecificationId = 1,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2021, 12, 26, 1, 40, 0, 358, DateTimeKind.Local).AddTicks(5362),
                            Day = "Thursday",
                            IsOpen = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OpeningClosingSpecificationId = 1,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2021, 12, 26, 1, 40, 0, 358, DateTimeKind.Local).AddTicks(5502),
                            Day = "Friday",
                            IsOpen = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OpeningClosingSpecificationId = 1,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTime(2021, 12, 26, 1, 40, 0, 358, DateTimeKind.Local).AddTicks(5690),
                            Day = "Saturday",
                            IsOpen = false,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OpeningClosingSpecificationId = 1,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTime(2021, 12, 26, 1, 40, 0, 358, DateTimeKind.Local).AddTicks(5699),
                            Day = "Sunday",
                            IsOpen = false,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OpeningClosingSpecificationId = 1,
                            StatusId = 1
                        });
                });

            modelBuilder.Entity("FoodStoreMarket.Domain.Entities.OpeningClosingSpecification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Inactivated")
                        .HasColumnType("datetime2");

                    b.Property<string>("InactivatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RestaurantSpecificationId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantSpecificationId")
                        .IsUnique();

                    b.ToTable("OpeningClosingSpecifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2021, 12, 26, 1, 40, 0, 358, DateTimeKind.Local).AddTicks(4813),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RestaurantSpecificationId = 1,
                            StatusId = 1
                        });
                });

            modelBuilder.Entity("FoodStoreMarket.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfAccepted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfScheduledDelivery")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Inactivated")
                        .HasColumnType("datetime2");

                    b.Property<string>("InactivatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FoodStoreMarket.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Inactivated")
                        .HasColumnType("datetime2");

                    b.Property<string>("InactivatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductSpecificationId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("ProductSpecificationId")
                        .IsUnique()
                        .HasFilter("[ProductSpecificationId] IS NOT NULL");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2021, 12, 26, 1, 40, 0, 358, DateTimeKind.Local).AddTicks(5752),
                            MenuId = 1,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2021, 12, 26, 1, 40, 0, 358, DateTimeKind.Local).AddTicks(5760),
                            MenuId = 1,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1
                        });
                });

            modelBuilder.Entity("FoodStoreMarket.Domain.Entities.ProductSpecification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Inactivated")
                        .HasColumnType("datetime2");

                    b.Property<string>("InactivatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductSpecifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2021, 12, 26, 1, 40, 0, 358, DateTimeKind.Local).AddTicks(5787),
                            Description = "Kebab w Tortilli",
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kebab",
                            ProductId = 1,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2021, 12, 26, 1, 40, 0, 358, DateTimeKind.Local).AddTicks(5797),
                            Description = "Fizzy Drink",
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pepsi",
                            ProductId = 2,
                            StatusId = 1
                        });
                });

            modelBuilder.Entity("FoodStoreMarket.Domain.Entities.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Inactivated")
                        .HasColumnType("datetime2");

                    b.Property<string>("InactivatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MenuId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RestaurantSpecificationId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantSpecificationId")
                        .IsUnique();

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2021, 12, 26, 1, 40, 0, 358, DateTimeKind.Local).AddTicks(4019),
                            MenuId = 1,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RestaurantSpecificationId = 1,
                            StatusId = 1
                        });
                });

            modelBuilder.Entity("FoodStoreMarket.Domain.Entities.RestaurantSpecification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Inactivated")
                        .HasColumnType("datetime2");

                    b.Property<string>("InactivatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OpeningClosingSpecificationId")
                        .HasColumnType("int");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RestaurantSpecifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2021, 12, 26, 1, 40, 0, 358, DateTimeKind.Local).AddTicks(4153),
                            Description = "Best Kebab in Lodz",
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "BestKebab",
                            RestaurantId = 1,
                            StatusId = 1
                        });
                });

            modelBuilder.Entity("FoodStoreMarket.Domain.Entities.WorkingHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfEndWork")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfStartWork")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Inactivated")
                        .HasColumnType("datetime2");

                    b.Property<string>("InactivatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<decimal?>("WorkHours")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("WorkingHours");
                });

            modelBuilder.Entity("IndegrimentProductSpecification", b =>
                {
                    b.Property<int>("IndegrimentsId")
                        .HasColumnType("int");

                    b.Property<int>("ProductSpecificationsId")
                        .HasColumnType("int");

                    b.HasKey("IndegrimentsId", "ProductSpecificationsId");

                    b.HasIndex("ProductSpecificationsId");

                    b.ToTable("IndegrimentProductSpecification");
                });

            modelBuilder.Entity("OrderProduct", b =>
                {
                    b.Property<int>("OrdersId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("OrdersId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("OrderProduct");
                });

            modelBuilder.Entity("FoodStoreMarket.Domain.Entities.Client", b =>
                {
                    b.OwnsOne("FoodStoreMarket.Domain.ValueObjects.Adres", "Adres", b1 =>
                        {
                            b1.Property<int>("ClientId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Email")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FlatNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("HouseNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PostCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Street")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ClientId");

                            b1.ToTable("Clients");

                            b1.WithOwner()
                                .HasForeignKey("ClientId");
                        });

                    b.OwnsOne("FoodStoreMarket.Domain.ValueObjects.PersonName", "PersonName", b1 =>
                        {
                            b1.Property<int>("ClientId")
                                .HasColumnType("int");

                            b1.Property<string>("FirstName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LastName")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ClientId");

                            b1.ToTable("Clients");

                            b1.WithOwner()
                                .HasForeignKey("ClientId");
                        });

                    b.Navigation("Adres");

                    b.Navigation("PersonName");
                });

            modelBuilder.Entity("FoodStoreMarket.Domain.Entities.Employee", b =>
                {
                    b.HasOne("FoodStoreMarket.Domain.Entities.RestaurantSpecification", "RestaurantSpecification")
                        .WithMany("Employees")
                        .HasForeignKey("RestaurantSpecificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FoodStoreMarket.Domain.ValueObjects.Adres", "Adres", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Email")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FlatNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("HouseNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PostCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Street")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");

                            b1.HasData(
                                new
                                {
                                    EmployeeId = 1,
                                    City = "Lodz",
                                    Email = "mateusz.nowak@gmail.com",
                                    FlatNumber = "1",
                                    HouseNumber = "10",
                                    PhoneNumber = "112233445",
                                    PostCode = "94-042",
                                    Street = "Rajdowa"
                                },
                                new
                                {
                                    EmployeeId = 2,
                                    City = "Lodz",
                                    Email = "mariusz.gruszka@gmail.com",
                                    FlatNumber = "44",
                                    HouseNumber = "80",
                                    PhoneNumber = "987654321",
                                    PostCode = "94-042",
                                    Street = "Retkinska"
                                });
                        });

                    b.OwnsOne("FoodStoreMarket.Domain.ValueObjects.PersonName", "PersonName", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .HasColumnType("int");

                            b1.Property<string>("FirstName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LastName")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");

                            b1.HasData(
                                new
                                {
                                    EmployeeId = 1,
                                    FirstName = "Mateusz",
                                    LastName = "Nowak"
                                },
                                new
                                {
                                    EmployeeId = 2,
                                    FirstName = "Mariusz",
                                    LastName = "Gruszka"
                                });
                        });

                    b.Navigation("Adres");

                    b.Navigation("PersonName");

                    b.Navigation("RestaurantSpecification");
                });

            modelBuilder.Entity("FoodStoreMarket.Domain.Entities.Menu", b =>
                {
                    b.HasOne("FoodStoreMarket.Domain.Entities.Restaurant", "Restaurant")
                        .WithOne("Menu")
                        .HasForeignKey("FoodStoreMarket.Domain.Entities.Menu", "RestaurantId");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("FoodStoreMarket.Domain.Entities.OpeningClosingHours", b =>
                {
                    b.HasOne("FoodStoreMarket.Domain.Entities.OpeningClosingSpecification", "OpeningClosingSpecification")
                        .WithMany("OpeningClosingHours")
                        .HasForeignKey("OpeningClosingSpecificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FoodStoreMarket.Domain.ValueObjects.Time", "ClosingTime", b1 =>
                        {
                            b1.Property<int>("OpeningClosingHoursId")
                                .HasColumnType("int");

                            b1.Property<int>("Hour")
                                .HasColumnType("int");

                            b1.Property<int>("Minute")
                                .HasColumnType("int");

                            b1.Property<int>("Secound")
                                .HasColumnType("int");

                            b1.HasKey("OpeningClosingHoursId");

                            b1.ToTable("OpeningClosingHours");

                            b1.WithOwner()
                                .HasForeignKey("OpeningClosingHoursId");

                            b1.HasData(
                                new
                                {
                                    OpeningClosingHoursId = 1,
                                    Hour = 20,
                                    Minute = 0,
                                    Secound = 0
                                },
                                new
                                {
                                    OpeningClosingHoursId = 2,
                                    Hour = 20,
                                    Minute = 0,
                                    Secound = 0
                                },
                                new
                                {
                                    OpeningClosingHoursId = 3,
                                    Hour = 20,
                                    Minute = 0,
                                    Secound = 0
                                },
                                new
                                {
                                    OpeningClosingHoursId = 4,
                                    Hour = 20,
                                    Minute = 0,
                                    Secound = 0
                                },
                                new
                                {
                                    OpeningClosingHoursId = 5,
                                    Hour = 20,
                                    Minute = 0,
                                    Secound = 0
                                });
                        });

                    b.OwnsOne("FoodStoreMarket.Domain.ValueObjects.Time", "OpeningTime", b1 =>
                        {
                            b1.Property<int>("OpeningClosingHoursId")
                                .HasColumnType("int");

                            b1.Property<int>("Hour")
                                .HasColumnType("int");

                            b1.Property<int>("Minute")
                                .HasColumnType("int");

                            b1.Property<int>("Secound")
                                .HasColumnType("int");

                            b1.HasKey("OpeningClosingHoursId");

                            b1.ToTable("OpeningClosingHours");

                            b1.WithOwner()
                                .HasForeignKey("OpeningClosingHoursId");

                            b1.HasData(
                                new
                                {
                                    OpeningClosingHoursId = 1,
                                    Hour = 8,
                                    Minute = 0,
                                    Secound = 0
                                },
                                new
                                {
                                    OpeningClosingHoursId = 2,
                                    Hour = 8,
                                    Minute = 0,
                                    Secound = 0
                                },
                                new
                                {
                                    OpeningClosingHoursId = 3,
                                    Hour = 8,
                                    Minute = 0,
                                    Secound = 0
                                },
                                new
                                {
                                    OpeningClosingHoursId = 4,
                                    Hour = 8,
                                    Minute = 0,
                                    Secound = 0
                                },
                                new
                                {
                                    OpeningClosingHoursId = 5,
                                    Hour = 8,
                                    Minute = 0,
                                    Secound = 0
                                });
                        });

                    b.Navigation("ClosingTime");

                    b.Navigation("OpeningClosingSpecification");

                    b.Navigation("OpeningTime");
                });

            modelBuilder.Entity("FoodStoreMarket.Domain.Entities.OpeningClosingSpecification", b =>
                {
                    b.HasOne("FoodStoreMarket.Domain.Entities.RestaurantSpecification", "RestaurantSpecification")
                        .WithOne("OpeningClosingSpecification")
                        .HasForeignKey("FoodStoreMarket.Domain.Entities.OpeningClosingSpecification", "RestaurantSpecificationId");

                    b.Navigation("RestaurantSpecification");
                });

            modelBuilder.Entity("FoodStoreMarket.Domain.Entities.Order", b =>
                {
                    b.HasOne("FoodStoreMarket.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FoodStoreMarket.Domain.ValueObjects.Adres", "Adres", b1 =>
                        {
                            b1.Property<int>("OrderId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Email")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FlatNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("HouseNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PostCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Street")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("Adres");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("FoodStoreMarket.Domain.Entities.Product", b =>
                {
                    b.HasOne("FoodStoreMarket.Domain.Entities.Menu", "Menu")
                        .WithMany("Products")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodStoreMarket.Domain.Entities.ProductSpecification", "ProductSpecification")
                        .WithOne("Product")
                        .HasForeignKey("FoodStoreMarket.Domain.Entities.Product", "ProductSpecificationId");

                    b.Navigation("Menu");

                    b.Navigation("ProductSpecification");
                });

            modelBuilder.Entity("FoodStoreMarket.Domain.Entities.Restaurant", b =>
                {
                    b.HasOne("FoodStoreMarket.Domain.Entities.RestaurantSpecification", "RestaurantSpecification")
                        .WithOne("Restaurant")
                        .HasForeignKey("FoodStoreMarket.Domain.Entities.Restaurant", "RestaurantSpecificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RestaurantSpecification");
                });

            modelBuilder.Entity("FoodStoreMarket.Domain.Entities.RestaurantSpecification", b =>
                {
                    b.OwnsOne("FoodStoreMarket.Domain.ValueObjects.Adres", "Adres", b1 =>
                        {
                            b1.Property<int>("RestaurantSpecificationId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Email")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FlatNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("HouseNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PostCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Street")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("RestaurantSpecificationId");

                            b1.ToTable("RestaurantSpecifications");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantSpecificationId");

                            b1.HasData(
                                new
                                {
                                    RestaurantSpecificationId = 1,
                                    City = "Lodz",
                                    Email = "bestkebab@gmail.com",
                                    HouseNumber = "16",
                                    PhoneNumber = "123456789",
                                    PostCode = "94-042",
                                    Street = "Olimpijska"
                                });
                        });

                    b.Navigation("Adres");
                });

            modelBuilder.Entity("FoodStoreMarket.Domain.Entities.WorkingHours", b =>
                {
                    b.HasOne("FoodStoreMarket.Domain.Entities.Employee", "Employee")
                        .WithMany("WorkingHours")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("IndegrimentProductSpecification", b =>
                {
                    b.HasOne("FoodStoreMarket.Domain.Entities.Indegriment", null)
                        .WithMany()
                        .HasForeignKey("IndegrimentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodStoreMarket.Domain.Entities.ProductSpecification", null)
                        .WithMany()
                        .HasForeignKey("ProductSpecificationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderProduct", b =>
                {
                    b.HasOne("FoodStoreMarket.Domain.Entities.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodStoreMarket.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FoodStoreMarket.Domain.Entities.Employee", b =>
                {
                    b.Navigation("WorkingHours");
                });

            modelBuilder.Entity("FoodStoreMarket.Domain.Entities.Menu", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("FoodStoreMarket.Domain.Entities.OpeningClosingSpecification", b =>
                {
                    b.Navigation("OpeningClosingHours");
                });

            modelBuilder.Entity("FoodStoreMarket.Domain.Entities.ProductSpecification", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("FoodStoreMarket.Domain.Entities.Restaurant", b =>
                {
                    b.Navigation("Menu");
                });

            modelBuilder.Entity("FoodStoreMarket.Domain.Entities.RestaurantSpecification", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("OpeningClosingSpecification");

                    b.Navigation("Restaurant");
                });
#pragma warning restore 612, 618
        }
    }
}
